package com.example.fifteendays.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


val md_theme_light_primary = Color(0xFF8D437F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F1)
val md_theme_light_onPrimaryContainer = Color(0xFF390033)
val md_theme_light_secondary = Color(0xFF6F5867)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF9DAED)
val md_theme_light_onSecondaryContainer = Color(0xFF271623)
val md_theme_light_tertiary = Color(0xFF815342)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCF)
val md_theme_light_onTertiaryContainer = Color(0xFF321206)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEFDEE6)
val md_theme_light_onSurfaceVariant = Color(0xFF4F444A)
val md_theme_light_outline = Color(0xFF80747B)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF2)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFFACEA)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8D437F)
val md_theme_light_outlineVariant = Color(0xFFD2C2CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFACEA)
val md_theme_dark_onPrimary = Color(0xFF57124E)
val md_theme_dark_primaryContainer = Color(0xFF722B66)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F1)
val md_theme_dark_secondary = Color(0xFFDCBED1)
val md_theme_dark_onSecondary = Color(0xFF3E2A38)
val md_theme_dark_secondaryContainer = Color(0xFF56404F)
val md_theme_dark_onSecondaryContainer = Color(0xFFF9DAED)
val md_theme_dark_tertiary = Color(0xFFF5B9A3)
val md_theme_dark_onTertiary = Color(0xFF4C2618)
val md_theme_dark_tertiaryContainer = Color(0xFF663C2C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFEAE0E3)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFEAE0E3)
val md_theme_dark_surfaceVariant = Color(0xFF4F444A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD2C2CA)
val md_theme_dark_outline = Color(0xFF9B8D95)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1D)
val md_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val md_theme_dark_inversePrimary = Color(0xFF8D437F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFACEA)
val md_theme_dark_outlineVariant = Color(0xFF4F444A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFF4F8)
val DarkBlue = Color(0xFF002A47)
val light_DarkBlue = Color(0xFF00629D)
val light_onDarkBlue = Color(0xFFFFFFFF)
val light_DarkBlueContainer = Color(0xFFCFE5FF)
val light_onDarkBlueContainer = Color(0xFF001D33)
val dark_DarkBlue = Color(0xFF99CBFF)
val dark_onDarkBlue = Color(0xFF003354)
val dark_DarkBlueContainer = Color(0xFF004A78)
val dark_onDarkBlueContainer = Color(0xFFCFE5FF)

